### ISSUE TITLE
[S3 - PBI2] Mengelola status pengerjaan

### ISSUE THREAD

**Issue by dindatarbiya** [SI-RPL-2022/SI4301_B_MahasiswaLancer#17]
Sebagai client, client dapat melihat status pengerjaan projectnya sehingga client dapat mengetahui progress pengerjaan project yang di pesan sudah terselesaikan atau belum

![PESAN JASA(6)](https://user-images.githubusercontent.com/92201930/174020965-29e9bff5-53e7-4b68-9819-d4f5eb5d7456.png)
![PESAN JASA(7)](https://user-images.githubusercontent.com/92201930/174021001-af5135c4-d784-4c6f-b8d3-8d153bb52631.png)
![PESAN JASA(8)](https://user-images.githubusercontent.com/92201930/174021052-5ab562e6-9c78-49c8-a7a7-a3a2d0787fca.png)
![PESAN JASA(9)](https://user-images.githubusercontent.com/92201930/174021085-873ad2f3-70a4-4c66-adc6-18a9df6d3a10.png)
![PESAN JASA(10)](https://user-images.githubusercontent.com/92201930/174021105-342ed533-21e1-42ff-8a54-294970b29219.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
