### ISSUE TITLE
[S3 - PBI3] Melakukan pembayaran

### ISSUE THREAD

**Issue by dindatarbiya** [SI-RPL-2022/SI4301_B_MahasiswaLancer#18]
Sebagai client, client dapat melakukan pembayaran sehingga client dapat langsung membayar pesanan projectnya sesuai dengan rincian pesanan dan pembayaran yang tertera

![PESAN JASA(3)](https://user-images.githubusercontent.com/92201930/172786516-7ab27402-42b7-4f60-9479-99b82dd414db.png)
![Rincian Pesanan](https://user-images.githubusercontent.com/92201930/172786586-5699862b-c024-45cf-8546-5aa207352c26.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
