### ISSUE TITLE
[S3 - PBI4] Memilih metode pembayaran

### ISSUE THREAD

**Issue by dindatarbiya** [SI-RPL-2022/SI4301_B_MahasiswaLancer#19]
Sebagai client, client dapat memilih metode pembayaran sehingga client termudahkan melakukan proses pembayaran sesuai dengan metode yang diinginkan

![Metode Pembayaran](https://user-images.githubusercontent.com/92201930/172787550-47191ee5-f727-43ae-9ffa-d61f0640385b.png)
![Metode Pembayaran (1)(1)](https://user-images.githubusercontent.com/92201930/174021601-bce3ba31-3d4d-4b59-867a-05ff2f5ac66e.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
