### ISSUE TITLE
[S3 - PBI5] Melihat status pembayaran

### ISSUE THREAD

**Issue by dindatarbiya** [SI-RPL-2022/SI4301_B_MahasiswaLancer#20]
Sebagai client, client dapat melihat status pembayaran sehingga client dapat mengetahui proses pembayarannya
apakah berhasil atau tidak

![PEMBAYARAN-ATM-BAYAR](https://user-images.githubusercontent.com/92201930/172647769-915b6842-d624-4d55-b0f8-05f3470b7c68.png)

**Comment by tienfkusumasari** [comment]
done (SP3)

**Comment by tienfkusumasari** [comment]
automatic rtesting di tambah case untuk auto increment di order id
