### ISSUE TITLE
[S3 - PBI6] Mengajukan pesanan jasa

### ISSUE THREAD

**Issue by dindatarbiya** [SI-RPL-2022/SI4301_B_MahasiswaLancer#21]
Sebagai client, client dapat melakukan pengajuan pesanan jasa sehingga project client dapat segera dikerjakan oleh mahasiswa

![PESAN JASA(4)](https://user-images.githubusercontent.com/92201930/172907363-f7b94364-92e1-4cbc-a592-1bb5f943a594.png)
![PESAN JASA(5)](https://user-images.githubusercontent.com/92201930/172907383-d348b12e-65d0-4ae5-a26a-d988884e8a4d.png)

**Comment by tienfkusumasari** [comment]
done (belum ada validasi tanmggal pemesanan) -
