### ISSUE TITLE
[S3 - PBI7] Mengkonfirmasi pesanan client

### ISSUE THREAD

**Issue by dindatarbiya** [SI-RPL-2022/SI4301_B_MahasiswaLancer#22]
Sebagai mahasiswa, mahasiswa dapat mengkonfirmasi pesanan client sehingga mahasiswa dapat menolak ataupun menerima pesanan project dari client

![DASHBOARD(1)](https://user-images.githubusercontent.com/92201930/172908355-dea0b8fa-fc3b-4216-8e59-59a849daf2da.png)
![DASHBOARD(2)](https://user-images.githubusercontent.com/92201930/172908227-0845e34f-5fc6-40a6-90fb-1fd0b1d0b7c8.png)
![DASHBOARD(3)](https://user-images.githubusercontent.com/92201930/172908239-4f0655e6-8add-4272-a179-5ed4997af602.png)

**Comment by tienfkusumasari** [comment]
close (SP3)

**Comment by tienfkusumasari** [comment]
ada bug pada saat sknario test nya di jalankan ....nama profil tidak terganti

**Comment by tienfkusumasari** [comment]
done (SP3) 
note tidak bisa di trace kalau status di tolak dari sisi mahasiswa
